language: python
python:
  - "2.7"
# Apply only on main branches
branches:
  except:
    - /^feature.*$/

# command to run tests
script:
- python setup.py build
- python setup.py test -vv
- coverage run --source src/ test/main.py && coverage html
after_success:
  - coveralls
